### ISSUE TITLE
ttyFTx not  showing up

### ISSUE THREAD

**Issue by DevDebugger** [MichaelZaidman/hid-ft260#18]
I installed the driver, insmod the .ko file , ran the setenv script, however i am not able to see any ttyFTx device in /dev/. Am i missing a step?

**Comment by MichaelZaidman** [comment]
The UART support is available only in the separate uart branch and has not yet been merged into the main branch. However, please note that the uart branch does not include the GPIO support found in the main branch. If you don't need the GPIO support, you can use the uart branch. On the other hand, if you require both UART and GPIO support, I have created a local branch that includes UART support on top of GPIO support. I will upload this branch in the next few days.

**Comment by DevDebugger** [comment]
thank you! was this branch every uploaded?

**Comment by MichaelZaidman** [comment]
Yes, I merged it into the main branch right now.

**Comment by MichaelZaidman** [comment]
Have you had a chance to try it? Can we close the ticket?
