### ISSUE TITLE
:question: How does one modify module attributes ( e.g clock or clock_ctl) ? 

### ISSUE THREAD

**Issue by catalinbalteanu** [MichaelZaidman/hid-ft260#4]

**Comment by MichaelZaidman** [comment]
You will need to figure out the ft260 device on the USB bus under sysfs.
Once you find it, you will see all available attributes.
For example, to set the i2c clock to 400KHz on my system, I run this command: 
```
sudo bash -c 'echo 400 > /sys/bus/usb/devices/2-2/2-2\:1.0/0003\:0403\:6030.0002/clock' 
```

**Comment by catalinbalteanu** [comment]
Thanks, works perfectly !
